Linux stage4
albertofwb/security-check-tool pull request #13
Opened 2020-11-08 13:14 UTC by x-Long

linux 后四个完善

2020-11-08 15:44 UTC, x-Long commented
sudo命令需要开启root权限

流程如下：
http://www.xitongzhijia.net/xtjc/20200621/181813.html

2020-11-09 02:45 UTC, albertofwb commented on native/linux_os.py
> +        with os.popen('sudo dmidecode --type memory') as fd:
不要用 sudo 或 root 

想办法以普通用户身份获取内存信息

2020-11-09 02:49 UTC, albertofwb requested changes

2020-11-09 02:49 UTC, albertofwb commented on native/linux_os.py
> +        path_list = get_all(path=r'/lib/modules/4.19.0-6-amd64/kernel/drivers')
得考虑系统升级后，这个目录名是否会根据版本而改变

4.19.0-6-amd64

2020-11-09 02:49 UTC, albertofwb commented on native/linux_os.py
> +        for i in range(len(path_list)):
`path_list` 本身就可以枚举

`for file_path in path_list`

2020-11-09 02:49 UTC, albertofwb commented on native/linux_os.py
> +        with os.popen('sudo dmidecode --type memory') as fd:
内存信息作用不大，枚举所有网卡名称和mac地址吧

2020-11-11 02:03 UTC, albertofwb approved these changes

2020-11-11 02:03 UTC, merged