WIP: nux下面的前三个
albertofwb/security-check-tool pull request #2
Opened 2020-11-02 01:37 UTC by jeffguorg

Linux下的get_usb_storage_device_using_records暂时是所有USB设备

看起来另一个人提交了Windows的实现，我晚一点把这部分revert掉

2020-11-03 02:32 UTC, jeffguorg commented
@albertofwb usb的之前都是用dmesg解析出来的，并不可靠，只是能临时用一下，而且这种方法无法辨认android设备。

更可靠的方法是使用udev建立规则捕获usb事件。比如说参考https://github.com/M0Rf30/android-udev-rules，来捕捉手机事件

如果dmesg这种方法足够的话，我就改成ready for review了

2020-11-03 05:15 UTC, jeffguorg commented
沟通之后，涉及到usb的实现都会改为udev

2020-11-06 03:25 UTC, albertofwb requested changes
所有时间，请统一使用  YYYY-MM-DD hh:mm:ss 这种格式

2020-11-06 03:25 UTC, albertofwb commented on native/linux_os.py
> +        return filter(lambda record: 'com.qihoo.360safe' == record.get("name"), self.get_installed_anti_virus_software_records())
循环调用自己，后面应该是 `get_installed_software_records` 吧

2020-11-06 03:25 UTC, albertofwb commented on native_os.py
> +
native_os 你别动，下面写的功能在 runner.py 里都有

用 checkout 还原下此文件

2020-11-06 03:25 UTC, albertofwb commented on requirements-win.txt
> -
该文件的空白行被你的编辑器吃了

2020-11-06 03:25 UTC, albertofwb commented on requirements-win.txt
> -
你应该修改下requirements-linux.txt

2020-11-06 03:25 UTC, albertofwb commented on native/linux/README.md
> +Linux实现所需的配置文件和脚本。需要安装时放置到对应路径中
麻烦子 linux 这个目录下提供一个脚本，可以一键配置文件
将对应配置文件拷贝到正确位置，并使之立刻生效

2020-11-11 02:41 UTC, albertofwb requested changes

2020-11-11 02:41 UTC, albertofwb commented on native/linux_os.py
> -        pass
为何不使用  `dpkg -l` 这样可以省掉 dbus 依赖

2020-11-11 02:41 UTC, albertofwb commented on native/linux_os.py
> -        pass
我们客户端有很大一部分情况是离线安装的，无法安装系统依赖 python-gobject and gobject-introspection-runtime

因此麻烦用其他方法替代 dbus 的实现

2020-11-11 02:41 UTC, albertofwb commented on native/linux_os.py
> +        for desktop_file in os.listdir(os.path.expanduser("~/.local/share/RecentDocuments")):
~/.local/share/RecentDocuments
不一定总是存在，在我的 uos20 中没有此文件

2020-11-11 03:50 UTC, jeffguorg commented on native/linux_os.py
> -        pass
done

2020-11-11 03:53 UTC, jeffguorg commented on abstract_os.py
> +
呃，vim可能没自动处理空行

2020-11-13 02:08 UTC, albertofwb commented
获取已安装软件记录出错
***************** get_installed_software_records *****************
{'name': 'accountsservice', 'version': '0.6.45-2', 'description': 'query and manipulate user account information\nThe AccountService project provides a set of D-Bus\ninterfaces for querying and manipulating user account\ninformation and an implementation of these interfaces,\nbased on the useradd, usermod and userdel commands.'}
Traceback (most recent call last):
  File "/home/vmware-uos/security-check-tool/runner.py", line 51, in run_methods
    spent_ms, result_count = run_instance_method(method_name)
  File "/home/vmware-uos/security-check-tool/runner.py", line 20, in run_instance_method
    for i, item in enumerate(generator):
  File "/home/vmware-uos/security-check-tool/native/linux_os.py", line 157, in get_installed_software_records
    name, version = lines[0].strip().split()
ValueError: too many values to unpack (expected 2)

获取服务异常
***************** get_services_records *****************
{'name': 'accounts-daemon.service', 'display_name': 'Accounts Service', 'start_type': 'auto', 'process_id': 843, 'is_system_service': True, 'status': 'running'}
Traceback (most recent call last):
  File "/home/vmware-uos/security-check-tool/runner.py", line 51, in run_methods
    spent_ms, result_count = run_instance_method(method_name)
  File "/home/vmware-uos/security-check-tool/runner.py", line 20, in run_instance_method
    for i, item in enumerate(generator):
  File "/home/vmware-uos/security-check-tool/native/linux_os.py", line 183, in get_services_records
    "start_type": "auto" if service_units[name] == "enabled" else "disabled" if service_units[name] == "masked" else "manual",
KeyError: 'apparmor.service'

网络信息，缺少进程名和pid
***************** get_current_network_records *****************
{'protocol': 'udp', 'local_ip': '192.168.114.120', 'local_port': 138, 'remote_ip': '', 'remote_port': 0, 'status': 'none'}

2020-11-16 08:01 UTC, albertofwb approved these changes

2020-11-16 08:17 UTC, merged